carts/urls.py
from django.urls import path, include
from .views import cart_home, add_to_cart, remove_from_cart, checkout_home, checkout_shipping, success_payment

app_name = 'carts'

urlpatterns = [
    path('', cart_home, name='cart'),
    path('add_cart/', add_to_cart, name='add_to_cart'),
    path('remove_from_cart/', remove_from_cart, name='remove_from_cart'),
    path('checkout/', checkout_home, name='checkout_home'),
    path('checkout_shipping/', checkout_shipping, name='checkout_shipping'),
    path('success_payment/', success_payment, name='success_payment')
]

hascoffee/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import home_page
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('', home_page, name='home'),
    path('admin/', admin.site.urls),
    path('products/', include('products.urls')),
    path('account/', include('accounts.urls')),
    path('cart/', include('carts.urls', namespace='carts')),
    path('search/', include('search.urls')),
    path('accounts/', include('accounts.passwords.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

search/urls.py
from django.urls import path, include
from .views import search

urlpatterns = [
    path('', search, name='search'),
]

carts/models.py
from django.db import models
from django.conf import settings
from products.models import Product
from django.db.models.signals import m2m_changed, pre_save, post_save
from django.core.validators import MaxValueValidator, MinValueValidator
from decimal import Decimal

User = settings.AUTH_USER_MODEL


class CartManager(models.Manager):
    def new_or_get(self, request):
        cart_id = request.session.get("cart_id", None)
        qs = self.get_queryset().filter(id=cart_id)
        if qs.count() == 1:
            new_obj = True
            cart_obj = qs.first()
            if request.user.is_authenticated and cart_obj.user is None:
                cart_obj.user = request.user
                cart_obj.save()
        else:
            cart_obj = Cart.objects.new(user=request.user)
            new_obj = True
            request.session['cart_id'] = cart_obj.id
        return cart_obj, new_obj

    def new(self, user=None):
        user_obj = None
        if user is not None:
            if user.is_authenticated:
                user_obj = user
        return self.model.objects.create(user=user_obj)

class CartItem(models.Model):
    cart = models.ForeignKey('Cart', null=True, blank=True, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=0, validators=[MaxValueValidator(50), MinValueValidator(1)])
    line_total = models.DecimalField(default=0.00, max_digits=100, decimal_places=2)
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        try:
            return str(self.product.title)
        except:
            return self.product.title

class Cart(models.Model):
    user = models.ForeignKey(User, blank=True, null=True, on_delete=models.CASCADE)
    products = models.ManyToManyField(Product, blank=True)
    total = models.DecimalField(default=0.00, max_digits=100, decimal_places=2)
    updated = models.DateTimeField(auto_now=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    objects = CartManager()

    def __str__(self):
        return str(self.id)

def m2m_changed_cart_receiver(sender, instance, action, *args, **kwargs):
    if action == 'post_add' or action == 'post_remove' or action == 'post_clear':
        products = instance.products.all()
        total = 0
        for x in products:
            total += x.price
        instance.total = total
        instance.save()

m2m_changed.connect(m2m_changed_cart_receiver, sender=Cart.products.through)



# def cartitem_receiver(sender, instance, *args, **kwargs):
#     cartItem = CartItem.objects.filter(cart=instance.cart.id)
#     total = 0
#     for x in cartItem:
#         total += x.line_total

#     instance.cart.total = total
#     instance.cart.save()


# post_save.connect(cartitem_receiver, sender=CartItem)

search/models.py
from django.db import models

# Create your models here.

search/views.py
from django.shortcuts import render
from products.models import Product

def search(request):
    context = {}
    query = request.GET.get('q', None)
    if query is not None:
        object_list = Product.objects.search(query)
        context = {
            "object_list": object_list
        }
    return render(request, 'search.html', context)

templates/cart_home.html
{% extends 'base.html' %}
{% load static %}
{% block base_head%}
<link rel="stylesheet" href="{% static 'css/header.css' %}">
<link rel="stylesheet" href="{% static 'css/footer.css' %}">
<link rel="stylesheet" href="{% static 'css/breadcrumb.css' %}">

<link rel="stylesheet" href="{% static 'css/cart_home.css' %}">

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
{% endblock %}

{% block content %}


{% include 'snippets/header.html' with headerstyle="grey-header" %}

{% if cart_items %}
<div class="cart_home">
    <div class="section-name">Your Cart</div>
    <div class="cart-grid">
        <div class="cart-grid-item">
            <div class="div">
                <div class="cart-grid-item-header">
                    <span class="inside-1">Price</span>
                    <span class="inside-2">Quantity</span>
                    <span class="inside-3">Total</span>
                </div>
                {% for cart_item in cart_items %}
                <div class="cart_grid-item-content">
                    <div class="grid_item_img">
                        <img src="{{cart_item.product.photo_main.url}}" alt="">

                    </div>
                    <div class="grid_item_content">
                        <h2><a href="{{cart_item.product.get_absolute_url}}">{{cart_item.product.title}}</a></h2>
                        <p>Roasted Whole Beans 250g</p>
                        <p style="color: #e20613;">
                            <form action="{% url 'carts:remove_from_cart' %}" name="" method="POST">
                                {% csrf_token %}
                                <input hidden name="product_id" value='{{cart_item.product.id}}'>
                                <input hidden name="quantity" value='0'>
                                <button class="quantity-button">Remove</button>
                            </form>
                        </p>
                    </div>
                    <div class="grid_item_price">
                        £ {{cart_item.product.price}}
                    </div>
                    <div class="grid_item_quantity">
                        <div class="quantity">
                            <div class="quantity-buttons">
                                <form action="{% url 'carts:remove_from_cart' %}" name="" method="POST">
                                    {% csrf_token %}
                                    <input hidden name="product_id" value='{{cart_item.product.id}}'>
                                    <input hidden name="quantity" value='1'>
                                    <button class="quantity-button">&lt;</button>
                                </form>
                                <div style="margin-top: 3px; font-weight: bolder">{{cart_item.quantity}}</div>
                                <form action="{% url 'carts:add_to_cart' %}" name="" method="POST">
                                    {% csrf_token %}
                                    <input hidden name="product_id" value='{{cart_item.product.id}}'>
                                    <input hidden name="quantity" value='1'>
                                    <button class="quantity-button">&gt;</button>
                                </form>
                            </div>
                        </div>
                    </div>
                    <div class="grid_item_total">
                        £ {{cart_item.line_total}}
                    </div>
                </div>
                {% endfor %}
            </div>
            <div class="cart_total">
                <div>Subtotal: <span style="color:#e20613; font-weight:bolder;">£{{cart.total}}</span></div>
                <div>Tax included and shipping calculated at checkout</div>
            </div>
            <div class="checkout">
                <a href="{% url 'carts:checkout_home' %}" class="news-button btn-checkout">
                    Checkout &rarr;
                </a>
            </div>
        </div>
    </div>
</div>
{% else %}
<div class="cart_home">
<div class="empty-cart">
    <h2 style="color: #e20613;font-size: 3rem;">Your Cart</h2>
    <p style="color: #534b4b; font-size: 2rem">Your cart is currently empty.</p>
    <p style="color: #534b4b; font-size: 2rem">Continue browsing <a class='here-link' href="{% url 'product_list' %}">here</a>.</p>
</div>


</div>
{% endif %}

{% include 'snippets/footer.html' %}




{% endblock %}

templates/checkout.html
{% extends 'base.html' %}
{% load static %}
{% block base_head%}
<link rel="stylesheet" href="{% static 'css/checkout.css' %}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
{% endblock %}

{% block content %}
<form id="logoutform" action="{% url 'logout' %}" method="POST">
  {% csrf_token %}
</form>
<div class="checkout-page">
    <div class="checkout-page-left">
        <div class="shipping-content">
            <div class="checkout-left-title">
                Hascoffee
            </div>
            <form action="{% url 'carts:checkout_shipping' %}" method="POST">
              {% csrf_token %}
            <div class="checkout-left-title-contact-info">
                <div class="contact-info">Contact information</div>
                {% if request.user.is_authenticated %}
                {% else %}
                <div class="contact-login">
                  <p>
                      <span>Already have an account? <a class="login_link" href="{% url 'login' %}">Log in</a></span>
                  </p>
              </div>
              {% endif %}
            </div>
            {% if request.user.is_authenticated %}
            <div class="user-logged">
              <div class="user-logged-img">
                <img class="user-img" src="{% static 'img/user.png' %}" alt="" srcset="">
              </div>
              <div class="user-logged-content">
                {{request.user.first_name}} {{request.user.last_name}} ({{request.user.email}})
                      <input type="hidden" name='next' value='{% url "carts:checkout_home" %}' form="logoutform">
                      <button class="checkout-logout-button" form="logoutform">Logout</button>
              </div>
            </div>
            {% else %}
            <div class="input-group full-line email-form">
              <input class="form-input" name="email" type="text" required>
              <span class="highlight"></span>
              <span class="bar"></span>
              <label>Email</label>
            </div>
            {% endif %}

            <div class="notify">
                <input type="checkbox" name="" id="" style="margin-right: 1rem;"><span style="font-size: 1.5rem;">Keep me up to date on news and exclusive offers</span>
            </div>
            <div class="checkout-shipping">
                <h2 class="shipping-title">
                    Shipping address
                </h2>
                {% if user.is_authenticated%}
                <input type="hidden" name="email" value="{{request.user.email}}">
                {% endif %}
                <div class="input-group">
                    <input class="form-input" type="text" name='first_name' required>
                    <span class="highlight"></span>
                    <span class="bar"></span>
                    <label>First name</label>
                  </div>
                  <div class="input-group">
                    <input class="form-input" type="text"  name='last_name' required>
                    <span class="highlight"></span>
                    <span class="bar"></span>
                    <label>Last name</label>
                  </div>
                  <div class="input-group full-line" name='company'>
                    <input class="form-input" type="text" >
                    <span class="highlight"></span>
                    <span class="bar"></span>
                    <label>Company (optional)</label>
                  </div>
                  <div class="input-group full-line">
                    <input class="form-input" type="text" name='address_1' required>
                    <span class="highlight"></span>
                    <span class="bar"></span>
                    <label>Address</label>
                  </div>
                  <div class="input-group full-line">
                    <input class="form-input" type="text" name='address_2'>
                    <span class="highlight"></span>
                    <span class="bar"></span>
                    <label>Apartment, suite, etc.(optional)</label>
                  </div>
                  <div class="input-group full-line">
                    <input class="form-input" type="text"  name='city' required>
                    <span class="highlight"></span>
                    <span class="bar"></span>
                    <label>City</label>
                  </div>
                  <div class="input-group">
                    <input class="form-input" type="text" name='country' required>
                    <span class="highlight"></span>
                    <span class="bar"></span>
                    <label>County/region</label>
                  </div>
                  <div class="input-group">
                    <input class="form-input" type="text" name='post_code' required>
                    <span class="highlight"></span>
                    <span class="bar"></span>
                    <label>Postcode</label>
                  </div>
                  <div class="input-group full-line" name='phone'>
                    <input class="form-input" type="text" >
                    <span class="highlight"></span>
                    <span class="bar"></span>
                    <label>Phone(optional)</label>
                  </div>
            </div>
            <div class="shopping-footer">
                <a href="{% url 'carts:cart' %}" class="return-link">&lt; Return to cart</a>
                <button class="news-button">
                    Continue to shopping
                </button>
            </div>
            </form>
        </div>
    </div>
    <div class="checkout-page-right">
      <div class="checkout-page-wrap">
        <div class="checkout-products">
          {% for cart_item in cart_items %}
          <div class="checkout-single-product">
              <div class="product-img">
                <img src="{{cart_item.product.photo_main.url}}" alt="" srcset="">
                <div class="img-number"><span class="img-span">{{cart_item.quantity}}</span></div>
              </div>
              <div class="product-title">
                {{cart_item.product.title}}
              </div>
              <div class="product-price">
                £{{cart_item.line_total}}
              </div>
          </div>
          {% endfor %}
        </div>
        <div class="total-sum">
          <div class="checkout-total">
            <span style="color: white; font-size: 2rem">Cart total:</span>
            <span style="color: white; font-size: 2.5rem">£{{cart.total}}</span>
          </div>
        </div>

      </div>
    </div>
</div>
{% endblock %}

templates/checkout_shipping.html
{% extends 'base.html' %}
{% load static %}
{% block base_head%}
<link rel="stylesheet" href="{% static 'css/checkout.css' %}">
<link rel="stylesheet" href="{% static 'css/checkout-shipping.css' %}">

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
{% endblock %}

{% block content %}
<div class="checkout-page">
    <div class="checkout-page-left">
        <div class="shipping-content">
            <div class="checkout-left-title">
                Hascoffee
            </div>
            <div class="shipping-table-wrap">
              <div class="shipping-table" style="border-bottom: 1px solid #d9d9d9;">
                <div class="shipping-contact">
                  <p style="color: #7e7e7e;">Contact: </p>
                  <p>{{billing_profile.email}}</p>
                  <a href="{% url 'carts:checkout_home' %}" class="ship-table-link">Change</a>
                </div>
              </div>
              <div class="shipping-table">
                <div class="shipping-contact">
                  <p style="color: #7e7e7e">Ship to: </p>
                  <p>{% if address.company %} {{address.company}} {% endif %} {{address.address_1}}, {{address.city}}, {{address.post_code}}, {{address.country}} </p>
                  <a href="{% url 'carts:checkout_home' %}" class="ship-table-link">Change</a>
                </div>
              </div>
            </div>

            <div class="shopping-footer">
                <a href="{% url 'carts:checkout_home' %}" class="return-link">&lt; Return to information</a>
                <form action="{% url 'carts:success_payment' %}" method="POST">
                {% csrf_token%}
                <input type="hidden" name="is_done" value='success' >
                <button class="news-button">
                    Pay
                </button>
              </form>
            </div>
        </div>
    </div>
    <div class="checkout-page-right">
      <div class="checkout-page-wrap">
        <div class="checkout-products">
          {% for cart_item in cart_items %}
          <div class="checkout-single-product">
              <div class="product-img">
                <img src="{{cart_item.product.photo_main.url}}" alt="" srcset="">
                <div class="img-number"><span class="img-span">{{cart_item.quantity}}</span></div>
              </div>
              <div class="product-title">
                {{cart_item.product.title}}
              </div>
              <div class="product-price">
                £{{cart_item.line_total}}
              </div>
          </div>
          {% endfor %}
        </div>
        <div class="total-sum">
          <div class="checkout-total">
            <span style="color: white; font-size: 1.5rem">Subtotal:</span>
            <span style="color: white; font-size: 1.5rem">£{{object.cart.total}}</span>
          </div>
          <div class="checkout-total">
            <span style="color: white; font-size: 1.5rem">Shipping:</span>
            <span style="color: white; font-size: 1.5rem">£{{object.shipping_total}}</span>
          </div>
          <div class="checkout-total">
            <span style="color: white; font-size: 2rem">Total:</span>
            <span style="color: white; font-size: 2.5rem">£{{object.total}}</span>
          </div>
        </div>

      </div>
    </div>
</div>
{% endblock %}

templates/dashboard.html
{% extends 'base.html' %}
{% load static %}
{% block base_head%}
<link rel="stylesheet" href="{% static 'css/header.css' %}">
<link rel="stylesheet" href="{% static 'css/footer.css' %}">
<link rel="stylesheet" href="{% static 'css/breadcrumb.css' %}">
<link rel="stylesheet" href="{% static 'css/dashboard.css' %}">

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
{% endblock %}
{% block content %}
{% include 'snippets/header.html' %}
{% include 'snippets/breadcrumb.html' with instance="Dashboard" %}
<div class="dashboard">
    <div class="login-form-left">
        {% include 'snippets/alert.html' %}
    <h3>
        Order History
    </h3>

    {% if carts %}
        {% for cart in carts %}
        <div style="border: 1px solid black; padding: 1rem; font-size: 1.2rem">
        Order number is: {{cart.order.order_id}}
            {% for item in cart.cartitem_set.all %}
                <div>
                    <span>{{item.product}} - {{item.quantity}} items x £{{item.product.price}} = {{item.line_total}}</span>
                </div>
            {% endfor %}
            Total price: £{{cart.total}}
        </div>
        {% endfor %}
    {% else%}
    <p style="color: #919191; font-size: 1.6rem">
        You haven't placed any orders yet.
    </p>
    {% endif %}

    </div>
    <div class="login-form-right">
        <div class="buttons">
            <a class="buy-button" href="{% url 'login' %}">Manage wishlist <span>&rarr;</span></a>
            <form action="{% url 'logout' %}">
                <button class="news-button btn-login"><span>Log out</span><span>&rarr;</button>
            </form>
        </div>
        <h2 class="login-form-title">Already have an account?</h2>
        <a href="" class="adresses">View Adresses</a>
    </div>

</div>
{% include 'snippets/footer.html' %}




{% endblock %}

templates/homepage.html
{% extends "base.html" %}
{% load static %}


{% block base_head%}
<link rel="stylesheet" href="{% static 'css/homepage.css' %}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
{% endblock %}

{% block content %}
{% url 'carts:cart' as cart_url %}

<div class="homapage">
  <!-- Carousel -->
  <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
      <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img class="d-block w-100" src="{% static 'img/coffee_hands.jpeg' %}" alt="First slide">
      </div>
      <div class="carousel-item">
        <img class="d-block w-100" src="{% static 'img/coffee_tree.jpg' %}" alt="Second slide">
      </div>
      <div class="carousel-item">
        <img class="d-block w-100" src="{% static 'img/artisan-coffee-beans.jpg' %}" alt="Third slide">
      </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
  <!-- Header sticked to carousel -->
  <div class="homepage-header">
    <ul class="header-nav">
      <li class="header-item">Wholesale</li>
      <li class="header-item">Resources</li>
      <li class="header-item">Community</li>
      <li class="header-item">Contact</li>
      <li class="header-item">Help</li>
    </ul>
    <div class="header-right-block">
      <div class="right-block-accaunt"><a href="{% url 'login' %}">Account</a></div>
      <div class="right-block-cart">
        <a href="{{cart_url}}">
          <span>
            <i class="fa fa-shopping-cart" style='color: white;'></i>Cart{% if request.session.cart_items %}: {{ request.session.cart_items }} {% else %} {% endif %}
          </span>
        </a>
    </div>
      <div class="right-block-form">
        <form action="">
            <input type="text">
          </form>
      </div>

    </div>
  </div>
  <div class="homepage-header-table">
    <div class="title">Hascoffee</div>
    <ul class="nav-link-main">
      <li class="nav-link nav-link-normal"><a href="{% url 'product_list' %}">Coffee</a></li>
      <li class="nav-link nav-link-normal"><a href="{% url 'product_list' %}">Subscriptions</a></li>
      <li class="nav-link nav-link-normal"><a href="{% url 'product_list' %}">Equipment</a></li>
      <li class="nav-link nav-link-normal"><a href="{% url 'product_list' %}">Merchandise</a></li>
      <li class="nav-link nav-link-normal"><a href="{% url 'product_list' %}">Other drinks</a></li>
    </ul>
  </div>
  <div class="best-product">
    <h2>New coffee</h2>
    <strong>El mega coffee</strong>
    <p>Finca Las Brumas Washed SL28</p>
  </div>
  <a class="buy-button" href="#">Check it out <span>&rarr;</span></a>
</div>

<!-- New products -->
<div class="new-section">
    <h2>New in!</h2>
    <div class="product-list-section">
      {% for obj in object_list %}
      <div class="product">
        <div class="new-product">
          <a href="{{ obj.get_absolute_url }}">
            <div class="product-pic">
              <img src="{{ obj.photo_main.url }}" alt="" >
            </div>
            <span class="product-title">{{ obj.title}}</span>
            <p class="product-content">{{ obj.ingridients}}</p>
            <p class="product-price">£{{obj.price}}</p>
          </a>
        </div>
      </div>
      {% endfor %}
    </div>
</div>

<!-- Subscription section -->
<div class="subscription-section">
  <div class="subscription">
    <div class="subs-feature">
        <h2>In My Mug coffee subscriptions</h2>
        <p>Not sure what an In My Mug coffee subscription is?</p>
        <a href="#" class="subs-a">Find out more here.</a>
        <a class="subs-button" href="#">View subscriptions<span>&rarr;</span></a>

      </div>
      <div class="subs-feature">
        <div class="icon">
          <img src="{% static 'img/red.png' %}" alt="" srcset="" class="icon-svg">
        </div>
    </div>
  </div>
</div>

<!-- Best selling products -->
<div class="new-section mt-3 ">
  <h2>Best sellers!</h2>
  <div class="product-list-section new-grid ">
    {% for obj in new_object_list %}
    <div class="product">
      <div class="new-product">
        <a href="{{obj.get_absolute_url }}">
          <div class="product-pic">
            <img src="{{ obj.photo_main.url }}" alt="" >
          </div>
          <span class="product-title">{{obj.title}}</span>
          <p class="product-content">{{obj.ingridients}}</p>
          <p class="product-price">£ {{obj.price}}</p>
        </a>
      </div>
     </div>
    {% endfor %}
  </div>
</div>

<!-- Abouts us -->
<div class="subscription-section about-us">
  <div class="subscription">
      <div class="subs-feature">
        <h2>About us</h2>
        <p>We're obsessed with the range of flavours that coffee can offer.</p>
        <p>We want to share those flavours, whilst making remarkable coffee more a those flavours, whilst making remarkable coffee more a those flavours, whilst making remarkable coffee more available, sustainable, and consistently delicious.</p>

      </div>
      <div class="subs-feature">
        <div class="icon coffee-img">
          <img src="{% static 'img/coffee-cup1.png' %}" alt="" srcset="" class="icon-svg">
        </div>
    </div>
  </div>
</div>


<div class="footer">
  <div class="homepage-footer">
    <div class="contact">
      <h3>Contact us</h3>
      <p>Email: <a href="#">orders@hasbean.co.uk</a></p>
      <p>Hasbean</p>
      <p>Unit 16, Ladford Covert</p>
      <p>Ladfordfields Industrial Estate</p>
      <p>Stafford</p>
      <p>ST18 9QL</p>
      <p>United Kingdom</p>
    </div>
    <div class="follow">
      <h3>Follow us</h3>
      <span class="folow-icon">
        <a href="#" class="fa fa-twitter"></a>
      </span>
      <span class="folow-icon">
        <a href="#" class="fa fa-facebook"></a>
      </span>
      <span class="folow-icon">
        <a href="#" class="fa fa-instagram"></a>
      </span>
      <span class="folow-icon">
        <a href="#" class="fa fa-youtube"></a>
      </span>
    </div>
    <div class="newsletter">
      <h3>Newsletter</h3>
      <p>Want to stay up to date with Hasbean via our newsletter?</p>
      <p>To subscribe, enter your details below.</p>
      <form action="" class="newsletter-form">
        <input type="text" class="news-name" placeholder="First name" required>
        <input type="text"class="news-surname" placeholder="Last name" required>
        <input type="email" class="news-email" placeholder="Email" required>
        <button class="news-button"><span>Subscribe</span><span>&rarr;</button>
      </form>
    </div>
    <div class="policy">
      <div class="policy-span">
        <span>Copyright © 2020, Hascofee</span>
        <span>All rights reserved</span>
        <span><a href="#">Privacy policy</a></span>
        <span><a href="#">Terms and Conditions</a></span>
      </div>
      <div class="policy-bottom">
        hasbean.co.uk uses cookies to help us improve your experience. By continuing to browse you are agreeing to our <a href="#">use of cookies</a>. Mmm cookies.
      </div>
    </div>
  </div>

</div>

</div>


{% endblock %}

templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block base_head%}
<link rel="stylesheet" type="text/css" href="{% static 'css/header.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/footer.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/breadcrumb.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
{% endblock %}

{% block content %}


{% include 'snippets/header.html' %}
{% include 'snippets/breadcrumb.html' with instance="Account" %}


<div class="login">
  <div class="login-form-left">
    {% include 'snippets/alert.html' %}

    <form action="{% url 'login' %}" method="POST">
      {% csrf_token %}
      <h2 class="login-form-title">Login</h2>
      <input type="hidden" name='next' {% if request.session.checkout == 'checkout' %} value='{% url "carts:checkout_home" %}' {% else %} value='{% url "dashboard"%}' {% endif %}>
      <input name="email" type="email" class="login-form-left-input" placeholder="Email" required>
      <input name="password" type="password" class="login-form-left-input" placeholder="Password" required>
      <button class="news-button btn-login"><span>Login</span><span>&rarr;</button>
    </form>
  </div>
  <div class="login-form-right">
    <h2 class="login-form-title">Create account</h2>
    <p>
      There's no need to create an account before shopping with us if you don't want to, but if you'd like to you can create one by clicking the link below.
    </p>
    <a class="buy-button" href="{% url 'register' %}">Create account <span>&rarr;</span></a>

  </div>
</div>
{% include 'snippets/footer.html' %}




{% endblock %}

templates/success_payment.html
{% extends 'base.html' %}
{% load static %}
{% block base_head%}
<link rel="stylesheet" href="{% static 'css/header.css' %}">
<link rel="stylesheet" href="{% static 'css/footer.css' %}">
<link rel="stylesheet" href="{% static 'css/breadcrumb.css' %}">

<link rel="stylesheet" href="{% static 'css/product_list.css' %}">

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
{% endblock %}

{% block content %}


{% include 'snippets/header.html' with headerstyle="grey-header" %}

<div class="pre-section">
  <div class="section-name">Thank you for your order</div>

</div>
<div class="success-payment">



</div>
{% include 'snippets/footer.html' %}




{% endblock %}